### ISSUE TITLE
Upload to Imgur not working

### ISSUE THREAD

**Issue by gdavid04** [VazkiiMods/Psi#747]
Log:
```
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: java.lang.IllegalArgumentException: URI is not absolute
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at java.net.URI.toURL(URI.java:1088)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraft.util.Util$OS.func_195642_a(Util.java:587)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at vazkii.psi.client.core.helper.SharingHelper.uploadAndOpen(SharingHelper.java:69)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at vazkii.psi.client.gui.GuiProgrammer.func_230430_a_(GuiProgrammer.java:473)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:297)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraft.client.main.Main.main(Main.java:184)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[20:05:52] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: java.lang.IllegalArgumentException: URI is not absolute
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at java.net.URI.toURL(URI.java:1088)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraft.util.Util$OS.func_195642_a(Util.java:587)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at vazkii.psi.client.core.helper.SharingHelper.uploadAndOpen(SharingHelper.java:69)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at vazkii.psi.client.gui.GuiProgrammer.func_230430_a_(GuiProgrammer.java:473)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:297)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraft.client.main.Main.main(Main.java:184)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[20:06:07] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: java.lang.IllegalArgumentException: URI is not absolute
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at java.net.URI.toURL(URI.java:1088)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraft.util.Util$OS.func_195642_a(Util.java:587)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at vazkii.psi.client.core.helper.SharingHelper.uploadAndOpen(SharingHelper.java:69)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at vazkii.psi.client.gui.GuiProgrammer.func_230430_a_(GuiProgrammer.java:473)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:297)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraft.client.main.Main.main(Main.java:184)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[20:06:30] [Render thread/INFO] [STDERR/]: [vazkii.psi.client.core.helper.SharingHelper:uploadAndOpen:71]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by Kamefrede** [comment]
Can't replicate. Seems to be a sporadic issue with their upload API.
